### ISSUE TITLE
Dialogs do not appear in FireFox

### ISSUE THREAD

**Issue by itsrachelfish** [Klikini/TicTacToe3#9]
Thank you for accepting my pull request! But... now there's a couple other things. :(

In FireFox, no dialog windows appear. Clicking the settings button generates this error in the console:

```
TypeError: J.t(...).sbJ is not a function           main.dart.js:5547:27
```

When the game is over, this error appears:

```
TypeError: J.t(...).sbI is not a function           main.dart.js:5562:27
```

Tested on both desktop and mobile.

**Comment by Klikini** [comment]
Firefox doesn't support the `<dialog>` element (I think Chrome is the only browser that does), so I changed it to a `.dialog` and `.dialog.open` CSS class system instead: https://github.com/Klikini/TicTacToe3/commit/01703eee095b5145cf9026497abca3f6d77e700d
